<?php
namespace App\Domains\Analytics\Http\Controllers;
use App\Domains\Analytics\Models\{AnalyticsDashboard, AnalyticsDataset, AnalyticsReport, KpiDefinition, KpiValue};
use App\Domains\Analytics\Services\AnalyticsService;
use App\Domains\Platform\Contracts\TenantContext;
use Illuminate\Http\{JsonResponse, Request};
class AnalyticsController
{
    public function __construct(private readonly AnalyticsService $analytics, private readonly TenantContext $tenant) {}
    public function kpis(Request $request): JsonResponse { $this->allow($request, 'analytics.view'); return response()->json(['data' => KpiDefinition::query()->where(fn ($q) => $q->whereNull('tenant_id')->orWhere('tenant_id', $this->tenant->id()))->with('values')->paginate(25)]); }
    public function createKpi(Request $request): JsonResponse { $this->allow($request, 'analytics.manage'); $data = $request->validate(['code' => ['required', 'alpha_dash', 'max:80'], 'name' => ['required', 'string', 'max:160'], 'category' => ['nullable', 'string'], 'calculation_type' => ['required', 'in:sum,count,average,avg,min,max'], 'definition' => ['required', 'array'], 'unit' => ['nullable', 'string', 'max:30'], 'frequency' => ['required', 'string', 'max:20']]); return response()->json(['data' => KpiDefinition::query()->create([...$data, 'tenant_id' => $this->tenant->id()])], 201); }
    public function calculate(Request $request, string $kpi): JsonResponse { $this->allow($request, 'analytics.manage'); $model = KpiDefinition::query()->where(fn ($q) => $q->whereNull('tenant_id')->orWhere('tenant_id', $this->tenant->id()))->findOrFail($kpi); $data = $request->validate(['from' => ['required', 'date'], 'to' => ['required', 'date', 'after_or_equal:from']]); return response()->json(['data' => $this->analytics->calculate($this->tenant->id(), $model, $data['from'], $data['to'])]); }
    public function dashboards(Request $request): JsonResponse { $this->allow($request, 'analytics.view'); return response()->json(['data' => AnalyticsDashboard::query()->where('tenant_id', $this->tenant->id())->latest()->paginate(25)]); }
    public function createDashboard(Request $request): JsonResponse { $this->allow($request, 'analytics.manage'); $data = $request->validate(['name' => ['required', 'string', 'max:160'], 'audience' => ['nullable', 'string'], 'layout' => ['required', 'array'], 'security_rules' => ['nullable', 'array']]); return response()->json(['data' => AnalyticsDashboard::query()->create([...$data, 'tenant_id' => $this->tenant->id(), 'created_by' => $request->user()->id])], 201); }
    public function values(Request $request, string $kpi): JsonResponse { $this->allow($request, 'analytics.view'); $model = KpiDefinition::query()->where(fn ($q) => $q->whereNull('tenant_id')->orWhere('tenant_id', $this->tenant->id()))->findOrFail($kpi); return response()->json(['data' => KpiValue::query()->where('tenant_id', $this->tenant->id())->where('kpi_definition_id', $model->id)->latest('period_end')->paginate(50)]); }
    public function forecast(Request $request, string $kpi): JsonResponse { $this->allow($request, 'analytics.view'); $model = KpiDefinition::query()->where(fn ($q) => $q->whereNull('tenant_id')->orWhere('tenant_id', $this->tenant->id()))->findOrFail($kpi); return response()->json(['data' => $this->analytics->forecast($this->tenant->id(), $model, (int) $request->integer('periods', 3))]); }
    public function datasets(Request $request): JsonResponse { $this->allow($request, 'analytics.view'); return response()->json(['data' => AnalyticsDataset::query()->where('tenant_id', $this->tenant->id())->paginate(25)]); }
    public function createDataset(Request $request): JsonResponse { $this->allow($request, 'analytics.manage'); $data = $request->validate(['name' => ['required', 'string', 'max:160'], 'source_type' => ['required', 'string', 'max:50'], 'definition' => ['required', 'array'], 'security_rules' => ['nullable', 'array']]); return response()->json(['data' => AnalyticsDataset::query()->create([...$data, 'tenant_id' => $this->tenant->id()])], 201); }
    public function reports(Request $request): JsonResponse { $this->allow($request, 'analytics.view'); return response()->json(['data' => AnalyticsReport::query()->where('tenant_id', $this->tenant->id())->paginate(25)]); }
    public function createReport(Request $request): JsonResponse { $this->allow($request, 'analytics.manage'); $data = $request->validate(['name' => ['required', 'string', 'max:160'], 'dataset_id' => ['nullable', 'uuid'], 'definition' => ['required', 'array'], 'schedule' => ['nullable', 'array'], 'delivery' => ['nullable', 'array']]); return response()->json(['data' => AnalyticsReport::query()->create([...$data, 'tenant_id' => $this->tenant->id()])], 201); }
    public function ingest(Request $request): JsonResponse { $this->allow($request, 'analytics.manage'); $data = $request->validate(['facts' => ['required', 'array'], 'facts.*.fact_type' => ['required', 'string'], 'facts.*.fact_date' => ['required', 'date'], 'facts.*.measures' => ['required', 'array']]); return response()->json(['data' => ['records_processed' => $this->analytics->ingest($this->tenant->id(), $data['facts'])]], 202); }
    public function refresh(Request $request): JsonResponse { $this->allow($request, 'analytics.manage'); $data = $request->validate(['pipeline' => ['required', 'string', 'max:80'], 'run_type' => ['sometimes', 'string', 'max:20']]); return response()->json(['data' => $this->analytics->refresh($this->tenant->id(), $data['pipeline'], $data['run_type'] ?? 'manual')], 202); }
    private function allow(Request $request, string $permission): void { $request->user()->hasPermission($permission) || abort(403); }
}
