<?php

namespace App\Domains\AiOperations\Enums;

enum AiInteractionLifecycle: string
{
    case REQUESTED = 'REQUESTED';
    case AUTHORIZED = 'AUTHORIZED';
    case POLICY_CHECKED = 'POLICY_CHECKED';
    case PROCESSING = 'PROCESSING';
    case TOOLS_EXECUTED = 'TOOLS_EXECUTED';
    case GROUNDING_VALIDATED = 'GROUNDING_VALIDATED';
    case RESPONSE_GENERATED = 'RESPONSE_GENERATED';
    case SAFETY_VALIDATED = 'SAFETY_VALIDATED';
    case DELIVERED = 'DELIVERED';
    case AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';
    case POLICY_BLOCKED = 'POLICY_BLOCKED';
    case TOOL_FAILED = 'TOOL_FAILED';
    case GROUNDING_FAILED = 'GROUNDING_FAILED';
    case MODEL_FAILED = 'MODEL_FAILED';
    case TIMEOUT = 'TIMEOUT';
    case SAFETY_BLOCKED = 'SAFETY_BLOCKED';
}
