<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('ai_providers', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('key',80); $t->string('provider_type',40); $t->json('configuration')->nullable(); $t->text('encrypted_credentials')->nullable(); $t->string('status',20)->default('active'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->unique(['tenant_id','key']); });
        Schema::create('ai_model_routes', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->uuid('provider_id'); $t->string('use_case',80); $t->string('model'); $t->unsignedInteger('priority')->default(100); $t->decimal('cost_limit',15,4)->nullable(); $t->json('settings')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->foreign('provider_id')->references('id')->on('ai_providers')->cascadeOnDelete(); });
        Schema::create('ai_prompts', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('key',100); $t->string('name'); $t->string('use_case',80); $t->unsignedInteger('version')->default(1); $t->string('status',20)->default('draft'); $t->longText('template'); $t->json('variables')->nullable(); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); $t->unique(['tenant_id','key','version']); });
        Schema::create('ai_skills', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('key',100); $t->string('name'); $t->uuid('prompt_id')->nullable(); $t->json('context_providers')->nullable(); $t->json('tool_permissions')->nullable(); $t->json('guardrails')->nullable(); $t->string('status',20)->default('active'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->foreign('prompt_id')->references('id')->on('ai_prompts')->nullOnDelete(); $t->unique(['tenant_id','key']); });
        Schema::create('ai_conversations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->uuid('skill_id')->nullable(); $t->string('role',40); $t->json('memory')->nullable(); $t->timestamp('last_message_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('skill_id')->references('id')->on('ai_skills')->nullOnDelete(); });
        Schema::create('ai_messages', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('conversation_id')->index(); $t->string('role',20); $t->longText('content'); $t->json('citations')->nullable(); $t->json('tool_calls')->nullable(); $t->json('guardrail_result')->nullable(); $t->timestamps(); $t->foreign('conversation_id')->references('id')->on('ai_conversations')->cascadeOnDelete(); });
        Schema::create('ai_knowledge_chunks', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('document_id')->nullable(); $t->string('source_type',40); $t->string('source_id',80); $t->unsignedInteger('chunk_index'); $t->longText('content'); $t->json('embedding_reference')->nullable(); $t->json('metadata')->nullable(); $t->timestamp('indexed_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('document_id')->references('id')->on('documents')->nullOnDelete(); $t->index(['tenant_id','source_type','source_id']); });
        Schema::create('ai_usage_logs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->uuid('provider_id')->nullable(); $t->uuid('skill_id')->nullable(); $t->string('model')->nullable(); $t->unsignedInteger('input_tokens')->default(0); $t->unsignedInteger('output_tokens')->default(0); $t->decimal('cost',15,6)->default(0); $t->unsignedInteger('latency_ms')->nullable(); $t->string('status',20); $t->timestamp('occurred_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('provider_id')->references('id')->on('ai_providers')->nullOnDelete(); $t->foreign('skill_id')->references('id')->on('ai_skills')->nullOnDelete(); });
        Schema::create('ai_feedback', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('message_id')->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->smallInteger('rating')->nullable(); $t->text('comments')->nullable(); $t->timestamps(); $t->foreign('message_id')->references('id')->on('ai_messages')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('ai_feedback'); Schema::dropIfExists('ai_usage_logs'); Schema::dropIfExists('ai_knowledge_chunks'); Schema::dropIfExists('ai_messages'); Schema::dropIfExists('ai_conversations'); Schema::dropIfExists('ai_skills'); Schema::dropIfExists('ai_prompts'); Schema::dropIfExists('ai_model_routes'); Schema::dropIfExists('ai_providers'); }
};
