<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('expense_categories', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->json('rules')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['tenant_id','name']); });
        Schema::create('expense_policies', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->json('assignment_rules')->nullable(); $t->json('rules')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('expense_claims', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->uuid('policy_id')->nullable(); $t->string('claim_number',50); $t->string('status',20)->default('draft'); $t->string('currency',3); $t->decimal('claimed_total',15,2)->default(0); $t->decimal('approved_total',15,2)->default(0); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('policy_id')->references('id')->on('expense_policies')->nullOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); $t->unique(['tenant_id','claim_number']); });
        Schema::create('expense_items', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('claim_id')->index(); $t->uuid('category_id')->nullable(); $t->date('expense_date'); $t->decimal('amount',15,2); $t->decimal('tax_amount',15,2)->default(0); $t->string('merchant')->nullable(); $t->text('description')->nullable(); $t->string('cost_center_id',80)->nullable(); $t->string('project_code')->nullable(); $t->string('payment_method',30)->nullable(); $t->json('receipt_document_ids')->nullable(); $t->json('mileage')->nullable(); $t->string('status',20)->default('pending'); $t->timestamps(); $t->foreign('claim_id')->references('id')->on('expense_claims')->cascadeOnDelete(); $t->foreign('category_id')->references('id')->on('expense_categories')->nullOnDelete(); });
        Schema::create('travel_requests', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->string('travel_type',20); $t->string('destination'); $t->text('purpose'); $t->date('start_date'); $t->date('end_date'); $t->decimal('estimated_cost',15,2)->nullable(); $t->json('itinerary')->nullable(); $t->decimal('per_diem',15,2)->default(0); $t->boolean('advance_required')->default(false); $t->string('status',20)->default('draft'); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('travel_advances', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->uuid('employee_id')->nullable()->index(); $t->uuid('travel_request_id')->nullable()->index(); $t->decimal('requested_amount',15,2); $t->decimal('disbursed_amount',15,2)->default(0); $t->decimal('settled_amount',15,2)->default(0); $t->string('status',20)->default('pending'); $t->timestamps(); });
        Schema::create('expense_budgets', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('scope_type',30); $t->string('scope_id',80); $t->decimal('budget_amount',15,2); $t->decimal('consumed_amount',15,2)->default(0); $t->date('starts_on'); $t->date('ends_on'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('expense_budgets'); Schema::dropIfExists('travel_advances'); Schema::dropIfExists('travel_requests'); Schema::dropIfExists('expense_items'); Schema::dropIfExists('expense_claims'); Schema::dropIfExists('expense_policies'); Schema::dropIfExists('expense_categories'); }
};
