<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('automation_templates', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('key',100); $t->string('name'); $t->string('category',50)->nullable(); $t->json('definition'); $t->string('status',20)->default('published'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->unique(['tenant_id','key']); });
        Schema::create('automations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('template_id')->nullable(); $t->string('key',100); $t->string('name'); $t->unsignedInteger('version')->default(1); $t->string('status',20)->default('draft'); $t->json('definition'); $t->json('settings')->nullable(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('template_id')->references('id')->on('automation_templates')->nullOnDelete(); $t->unique(['tenant_id','key','version']); });
        Schema::create('automation_triggers', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('automation_id')->index(); $t->string('trigger_type',50); $t->string('event',100)->nullable(); $t->string('cron_expression')->nullable(); $t->json('filter')->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); $t->foreign('automation_id')->references('id')->on('automations')->cascadeOnDelete(); });
        Schema::create('automation_variables', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->uuid('automation_id')->nullable(); $t->string('key',100); $t->string('scope',20); $t->string('value_type',30); $t->text('encrypted_value')->nullable(); $t->json('configuration')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->foreign('automation_id')->references('id')->on('automations')->cascadeOnDelete(); $t->unique(['automation_id','key']); });
        Schema::create('automation_executions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('automation_id')->index(); $t->string('trigger_type',50); $t->string('status',20); $t->string('current_node_id',100)->nullable(); $t->json('context')->nullable(); $t->unsignedInteger('duration_ms')->nullable(); $t->timestamp('started_at'); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('automation_id')->references('id')->on('automations')->cascadeOnDelete(); $t->index(['automation_id','status','started_at']); });
        Schema::create('automation_execution_steps', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('execution_id')->index(); $t->string('node_id',100); $t->string('node_type',40); $t->string('status',20); $t->json('input')->nullable(); $t->json('output')->nullable(); $t->text('error_message')->nullable(); $t->timestamp('started_at'); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('execution_id')->references('id')->on('automation_executions')->cascadeOnDelete(); });
        Schema::create('automation_human_tasks', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('execution_id')->index(); $t->string('node_id',100); $t->string('assignee_type',30); $t->string('assignee_id',80); $t->string('status',20)->default('pending'); $t->json('payload')->nullable(); $t->timestamp('due_at')->nullable(); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('execution_id')->references('id')->on('automation_executions')->cascadeOnDelete(); });
        Schema::create('automation_simulations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('automation_id')->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->json('test_data'); $t->json('result')->nullable(); $t->timestamp('simulated_at'); $t->timestamps(); $t->foreign('automation_id')->references('id')->on('automations')->cascadeOnDelete(); });
        Schema::create('automation_audits', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('automation_id')->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('action',40); $t->json('metadata')->nullable(); $t->timestamp('occurred_at'); $t->timestamps(); $t->foreign('automation_id')->references('id')->on('automations')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('automation_audits'); Schema::dropIfExists('automation_simulations'); Schema::dropIfExists('automation_human_tasks'); Schema::dropIfExists('automation_execution_steps'); Schema::dropIfExists('automation_executions'); Schema::dropIfExists('automation_variables'); Schema::dropIfExists('automation_triggers'); Schema::dropIfExists('automations'); Schema::dropIfExists('automation_templates'); }
};
