<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('api_products', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name'); $t->string('version',20); $t->string('status',20)->default('draft'); $t->json('openapi')->nullable(); $t->date('sunset_on')->nullable(); $t->timestamps(); $t->unique(['name','version']); });
        Schema::create('api_endpoints', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('api_product_id')->index(); $t->string('method',10); $t->string('path'); $t->string('resource',80); $t->json('required_scopes')->nullable(); $t->json('field_policies')->nullable(); $t->string('status',20)->default('published'); $t->timestamps(); $t->foreign('api_product_id')->references('id')->on('api_products')->cascadeOnDelete(); $t->unique(['api_product_id','method','path']); });
        Schema::create('api_clients', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('client_type',30); $t->string('client_identifier',100)->unique(); $t->text('encrypted_secret')->nullable(); $t->json('scopes'); $t->json('ip_allowlist')->nullable(); $t->string('status',20)->default('active'); $t->timestamp('secret_expires_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('api_rate_limit_policies', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('api_product_id')->nullable(); $t->uuid('api_client_id')->nullable(); $t->unsignedInteger('requests_per_minute'); $t->unsignedInteger('burst_limit')->nullable(); $t->timestamps(); $t->foreign('api_product_id')->references('id')->on('api_products')->nullOnDelete(); $t->foreign('api_client_id')->references('id')->on('api_clients')->nullOnDelete(); });
        Schema::create('api_request_logs', function (Blueprint $t) { $t->bigIncrements('id'); $t->uuid('tenant_id')->nullable()->index(); $t->uuid('api_client_id')->nullable(); $t->uuid('api_endpoint_id')->nullable(); $t->string('correlation_id',80)->index(); $t->unsignedSmallInteger('response_status'); $t->unsignedInteger('latency_ms'); $t->string('ip_address',45)->nullable(); $t->timestamp('requested_at'); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->foreign('api_client_id')->references('id')->on('api_clients')->nullOnDelete(); $t->foreign('api_endpoint_id')->references('id')->on('api_endpoints')->nullOnDelete(); });
        Schema::create('api_bulk_jobs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('api_client_id')->nullable(); $t->string('operation',30); $t->string('resource',80); $t->string('status',20)->default('queued'); $t->json('payload')->nullable(); $t->json('result')->nullable(); $t->string('download_document_id',80)->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('api_client_id')->references('id')->on('api_clients')->nullOnDelete(); });
        Schema::create('api_changelog_entries', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('api_product_id'); $t->string('change_type',30); $t->string('title'); $t->text('description')->nullable(); $t->date('published_on'); $t->timestamps(); $t->foreign('api_product_id')->references('id')->on('api_products')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('api_changelog_entries'); Schema::dropIfExists('api_bulk_jobs'); Schema::dropIfExists('api_request_logs'); Schema::dropIfExists('api_rate_limit_policies'); Schema::dropIfExists('api_clients'); Schema::dropIfExists('api_endpoints'); Schema::dropIfExists('api_products'); }
};
