<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('positions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('code',50); $t->string('title'); $t->string('family')->nullable(); $t->uuid('job_grade_id')->nullable(); $t->uuid('department_id')->nullable(); $t->uuid('business_unit_id')->nullable(); $t->uuid('cost_center_id')->nullable(); $t->uuid('branch_id')->nullable(); $t->uuid('reports_to_position_id')->nullable(); $t->decimal('fte',5,2)->default(1); $t->uuid('employment_type_id')->nullable(); $t->decimal('salary_min',15,2)->nullable(); $t->decimal('salary_max',15,2)->nullable(); $t->decimal('budget',15,2)->nullable(); $t->boolean('is_critical')->default(false); $t->string('status',20)->default('planned'); $t->timestamps(); $t->softDeletes(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('job_grade_id')->references('id')->on('job_grades')->nullOnDelete(); $t->foreign('department_id')->references('id')->on('departments')->nullOnDelete(); $t->foreign('business_unit_id')->references('id')->on('business_units')->nullOnDelete(); $t->foreign('cost_center_id')->references('id')->on('cost_centers')->nullOnDelete(); $t->foreign('branch_id')->references('id')->on('branches')->nullOnDelete(); $t->foreign('reports_to_position_id')->references('id')->on('positions')->nullOnDelete(); $t->foreign('employment_type_id')->references('id')->on('employment_types')->nullOnDelete(); $t->unique(['tenant_id','code']); });
        Schema::create('position_occupancies', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('position_id')->index(); $t->uuid('employee_id'); $t->date('starts_on'); $t->date('ends_on')->nullable(); $t->timestamps(); $t->foreign('position_id')->references('id')->on('positions')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->restrictOnDelete(); });
        Schema::create('headcount_plans', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->unsignedSmallInteger('year'); $t->string('status',20)->default('draft'); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('headcount_plan_lines', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('headcount_plan_id')->index(); $t->uuid('position_id')->nullable(); $t->uuid('department_id')->nullable(); $t->decimal('approved_fte',8,2)->default(0); $t->decimal('planned_fte',8,2)->default(0); $t->decimal('hiring_forecast',8,2)->default(0); $t->decimal('attrition_forecast',8,2)->default(0); $t->timestamps(); $t->foreign('headcount_plan_id')->references('id')->on('headcount_plans')->cascadeOnDelete(); $t->foreign('position_id')->references('id')->on('positions')->nullOnDelete(); $t->foreign('department_id')->references('id')->on('departments')->nullOnDelete(); });
        Schema::create('workforce_scenarios', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('scenario_type',30); $t->json('assumptions')->nullable(); $t->json('calculated_costs')->nullable(); $t->string('status',20)->default('draft'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('labor_budgets', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('scope_type',30); $t->string('scope_id',80); $t->date('starts_on'); $t->date('ends_on'); $t->decimal('salary_budget',18,2)->default(0); $t->decimal('benefit_budget',18,2)->default(0); $t->decimal('overtime_budget',18,2)->default(0); $t->decimal('recruitment_budget',18,2)->default(0); $t->decimal('training_budget',18,2)->default(0); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('position_requests', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('requester_employee_id'); $t->uuid('position_id')->nullable(); $t->string('request_type',30); $t->json('requested_changes')->nullable(); $t->string('status',20)->default('draft'); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('requester_employee_id')->references('id')->on('employees')->restrictOnDelete(); $t->foreign('position_id')->references('id')->on('positions')->nullOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('position_requests'); Schema::dropIfExists('labor_budgets'); Schema::dropIfExists('workforce_scenarios'); Schema::dropIfExists('headcount_plan_lines'); Schema::dropIfExists('headcount_plans'); Schema::dropIfExists('position_occupancies'); Schema::dropIfExists('positions'); }
};
