<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('job_templates', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('title'); $t->string('code',50); $t->json('description'); $t->json('requirements')->nullable(); $t->json('salary_range')->nullable(); $t->unsignedInteger('version')->default(1); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['tenant_id','code','version']); });
        Schema::create('requisitions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('company_id'); $t->uuid('department_id')->nullable(); $t->uuid('designation_id')->nullable(); $t->uuid('employment_type_id')->nullable(); $t->uuid('hiring_manager_id')->nullable(); $t->uuid('job_template_id')->nullable(); $t->unsignedInteger('vacancies'); $t->decimal('budget',15,2)->nullable(); $t->string('reason_type',30); $t->text('justification')->nullable(); $t->date('expected_joining_date')->nullable(); $t->string('status',20)->default('draft'); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('company_id')->references('id')->on('companies')->restrictOnDelete(); $t->foreign('department_id')->references('id')->on('departments')->nullOnDelete(); $t->foreign('designation_id')->references('id')->on('designations')->nullOnDelete(); $t->foreign('employment_type_id')->references('id')->on('employment_types')->nullOnDelete(); $t->foreign('hiring_manager_id')->references('id')->on('employees')->nullOnDelete(); $t->foreign('job_template_id')->references('id')->on('job_templates')->nullOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('candidates', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('first_name'); $t->string('last_name'); $t->string('email')->index(); $t->string('phone',40)->nullable(); $t->json('profile')->nullable(); $t->json('skills')->nullable(); $t->json('tags')->nullable(); $t->string('source',40)->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('job_postings', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('requisition_id'); $t->string('title'); $t->longText('description'); $t->string('status',20)->default('draft'); $t->timestamp('published_at')->nullable(); $t->timestamp('closes_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('requisition_id')->references('id')->on('requisitions')->cascadeOnDelete(); });
        Schema::create('applications', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('candidate_id'); $t->uuid('job_posting_id'); $t->string('stage',40)->default('applied'); $t->string('resume_path')->nullable(); $t->text('cover_letter')->nullable(); $t->json('notes')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('candidate_id')->references('id')->on('candidates')->cascadeOnDelete(); $t->foreign('job_posting_id')->references('id')->on('job_postings')->cascadeOnDelete(); $t->unique(['candidate_id','job_posting_id']); });
    }
    public function down(): void { Schema::dropIfExists('applications'); Schema::dropIfExists('job_postings'); Schema::dropIfExists('candidates'); Schema::dropIfExists('requisitions'); Schema::dropIfExists('job_templates'); }
};
