<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('rule_categories', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('name'); $t->string('domain',50)->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->unique(['tenant_id','name']); });
        Schema::create('rule_groups', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->uuid('category_id')->nullable(); $t->string('name'); $t->unsignedInteger('priority')->default(100); $t->boolean('is_active')->default(true); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->foreign('category_id')->references('id')->on('rule_categories')->nullOnDelete(); });
        Schema::create('business_rules', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->uuid('rule_group_id')->nullable(); $t->string('key',100); $t->string('name'); $t->string('domain',50); $t->string('trigger',50); $t->unsignedInteger('priority')->default(100); $t->unsignedInteger('version')->default(1); $t->string('status',20)->default('draft'); $t->dateTime('effective_from')->nullable(); $t->dateTime('effective_to')->nullable(); $t->string('execution_mode',20)->default('synchronous'); $t->json('conditions'); $t->json('actions'); $t->json('settings')->nullable(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->foreign('rule_group_id')->references('id')->on('rule_groups')->nullOnDelete(); $t->unique(['tenant_id','key','version']); });
        Schema::create('rule_bindings', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('business_rule_id')->index(); $t->string('subject_type',80); $t->string('event',50); $t->json('filter')->nullable(); $t->string('schedule_expression')->nullable(); $t->timestamps(); $t->foreign('business_rule_id')->references('id')->on('business_rules')->cascadeOnDelete(); });
        Schema::create('rule_executions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->uuid('business_rule_id')->index(); $t->string('subject_type',80)->nullable(); $t->string('subject_id',80)->nullable(); $t->string('status',20); $t->string('execution_mode',20); $t->unsignedInteger('duration_ms')->nullable(); $t->unsignedInteger('attempt')->default(1); $t->json('input')->nullable(); $t->json('output')->nullable(); $t->text('error_message')->nullable(); $t->timestamp('executed_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->foreign('business_rule_id')->references('id')->on('business_rules')->cascadeOnDelete(); $t->index(['business_rule_id','status','executed_at']); });
        Schema::create('rule_simulations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('business_rule_id')->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->json('test_data'); $t->json('result')->nullable(); $t->timestamp('simulated_at'); $t->timestamps(); $t->foreign('business_rule_id')->references('id')->on('business_rules')->cascadeOnDelete(); });
        Schema::create('rule_audits', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('business_rule_id')->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('action',40); $t->json('old_definition')->nullable(); $t->json('new_definition')->nullable(); $t->timestamp('occurred_at'); $t->timestamps(); $t->foreign('business_rule_id')->references('id')->on('business_rules')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('rule_audits'); Schema::dropIfExists('rule_simulations'); Schema::dropIfExists('rule_executions'); Schema::dropIfExists('rule_bindings'); Schema::dropIfExists('business_rules'); Schema::dropIfExists('rule_groups'); Schema::dropIfExists('rule_categories'); }
};
