<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('document_templates', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('code',80); $t->string('name'); $t->string('module',40)->nullable(); $t->string('language',10)->default('en'); $t->unsignedInteger('version')->default(1); $t->string('status',20)->default('draft'); $t->longText('content'); $t->json('layout')->nullable(); $t->json('merge_fields')->nullable(); $t->uuid('workflow_instance_id')->nullable(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); $t->unique(['tenant_id','code','language','version']); });
        Schema::create('document_generation_requests', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('template_id'); $t->string('requester_type',40); $t->string('requester_id',80); $t->string('target_type',40); $t->string('target_id',80); $t->json('context')->nullable(); $t->string('status',20)->default('pending'); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('template_id')->references('id')->on('document_templates')->restrictOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('generated_documents', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('template_id')->nullable(); $t->uuid('request_id')->nullable(); $t->uuid('document_id')->nullable(); $t->string('subject_type',40); $t->string('subject_id',80); $t->string('title'); $t->longText('rendered_content')->nullable(); $t->string('verification_token',100)->unique(); $t->string('status',20)->default('generated'); $t->timestamp('generated_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('template_id')->references('id')->on('document_templates')->nullOnDelete(); $t->foreign('request_id')->references('id')->on('document_generation_requests')->nullOnDelete(); $t->foreign('document_id')->references('id')->on('documents')->nullOnDelete(); });
        Schema::create('document_signatures', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('generated_document_id')->index(); $t->string('signer_type',40); $t->string('signer_id',80); $t->string('status',20)->default('pending'); $t->json('certificate_metadata')->nullable(); $t->timestamp('signed_at')->nullable(); $t->timestamps(); $t->foreign('generated_document_id')->references('id')->on('generated_documents')->cascadeOnDelete(); });
        Schema::create('template_audits', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('template_id')->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('action',30); $t->json('metadata')->nullable(); $t->timestamp('occurred_at'); $t->timestamps(); $t->foreign('template_id')->references('id')->on('document_templates')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('template_audits'); Schema::dropIfExists('document_signatures'); Schema::dropIfExists('generated_documents'); Schema::dropIfExists('document_generation_requests'); Schema::dropIfExists('document_templates'); }
};
