<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('benefit_plans', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('code',50); $t->string('benefit_type',40); $t->text('description')->nullable(); $t->string('provider')->nullable(); $t->date('effective_from'); $t->date('effective_to')->nullable(); $t->json('coverage')->nullable(); $t->json('eligibility_rules')->nullable(); $t->json('contribution_rules')->nullable(); $t->json('tax_rules')->nullable(); $t->string('status',20)->default('active'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['tenant_id','code']); });
        Schema::create('benefit_enrollment_periods', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->date('starts_on'); $t->date('ends_on'); $t->string('status',20)->default('draft'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('benefit_enrollments', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->uuid('benefit_plan_id'); $t->uuid('enrollment_period_id')->nullable(); $t->string('enrollment_type',30)->default('open_enrollment'); $t->string('status',20)->default('pending'); $t->date('effective_from'); $t->date('effective_to')->nullable(); $t->decimal('employee_contribution',15,2)->default(0); $t->decimal('employer_contribution',15,2)->default(0); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('benefit_plan_id')->references('id')->on('benefit_plans')->cascadeOnDelete(); $t->foreign('enrollment_period_id')->references('id')->on('benefit_enrollment_periods')->nullOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('benefit_dependents', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('benefit_enrollment_id')->nullable()->index(); $t->uuid('enrollment_id')->nullable()->index(); $t->string('name'); $t->string('relationship',40); $t->date('date_of_birth')->nullable(); $t->boolean('is_eligible')->default(true); $t->json('coverage')->nullable(); $t->timestamps(); });
        Schema::create('benefit_claims', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->uuid('benefit_enrollment_id')->nullable()->index(); $t->uuid('enrollment_id')->nullable()->index(); $t->string('claim_type',40); $t->decimal('claimed_amount',15,2); $t->decimal('approved_amount',15,2)->default(0); $t->string('status',20)->default('draft'); $t->json('document_ids')->nullable(); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); });
        Schema::create('provident_fund_transactions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->string('transaction_type',30); $t->decimal('employee_amount',15,2)->default(0); $t->decimal('employer_amount',15,2)->default(0); $t->decimal('interest_amount',15,2)->default(0); $t->date('transaction_date'); $t->json('metadata')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); });
        Schema::create('gratuity_policies', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->json('eligibility_rules'); $t->json('calculation_rules'); $t->boolean('is_active')->default(true); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('gratuity_policies'); Schema::dropIfExists('provident_fund_transactions'); Schema::dropIfExists('benefit_claims'); Schema::dropIfExists('benefit_dependents'); Schema::dropIfExists('benefit_enrollments'); Schema::dropIfExists('benefit_enrollment_periods'); Schema::dropIfExists('benefit_plans'); }
};
