<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('extension_publishers', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name'); $t->string('type',30); $t->string('email')->nullable(); $t->json('verification')->nullable(); $t->timestamps(); });
        Schema::create('extension_packages', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('publisher_id')->index(); $t->string('key',100)->unique(); $t->string('name'); $t->string('package_type',40); $t->text('description')->nullable(); $t->string('status',20)->default('draft'); $t->json('metadata')->nullable(); $t->timestamps(); $t->foreign('publisher_id')->references('id')->on('extension_publishers')->cascadeOnDelete(); });
        Schema::create('extension_versions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('package_id')->index(); $t->string('version',40); $t->json('manifest'); $t->string('checksum',128); $t->text('signature'); $t->json('compatibility'); $t->json('dependencies')->nullable(); $t->string('storage_path')->nullable(); $t->string('status',20)->default('draft'); $t->timestamp('published_at')->nullable(); $t->timestamps(); $t->foreign('package_id')->references('id')->on('extension_packages')->cascadeOnDelete(); $t->unique(['package_id','version']); });
        Schema::create('tenant_extensions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('package_id'); $t->uuid('version_id')->nullable(); $t->string('status',20)->default('installed'); $t->json('configuration')->nullable(); $t->json('granted_permissions')->nullable(); $t->timestamp('installed_at'); $t->timestamp('enabled_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('package_id')->references('id')->on('extension_packages')->cascadeOnDelete(); $t->foreign('version_id')->references('id')->on('extension_versions')->nullOnDelete(); $t->unique(['tenant_id','package_id']); });
        Schema::create('extension_licenses', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_extension_id')->index(); $t->string('license_type',30); $t->string('status',20); $t->timestamp('starts_at'); $t->timestamp('ends_at')->nullable(); $t->json('limits')->nullable(); $t->timestamps(); $t->foreign('tenant_extension_id')->references('id')->on('tenant_extensions')->cascadeOnDelete(); });
        Schema::create('tenant_brandings', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->unique(); $t->string('theme_mode',20)->default('light'); $t->json('branding'); $t->json('theme_variables')->nullable(); $t->json('localization')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('extension_health_checks', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_extension_id')->index(); $t->string('status',20); $t->json('details')->nullable(); $t->timestamp('checked_at'); $t->timestamps(); $t->foreign('tenant_extension_id')->references('id')->on('tenant_extensions')->cascadeOnDelete(); });
        Schema::create('extension_audits', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_extension_id')->nullable()->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('action',40); $t->json('metadata')->nullable(); $t->timestamp('occurred_at'); $t->timestamps(); $t->foreign('tenant_extension_id')->references('id')->on('tenant_extensions')->nullOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('extension_audits'); Schema::dropIfExists('extension_health_checks'); Schema::dropIfExists('tenant_brandings'); Schema::dropIfExists('extension_licenses'); Schema::dropIfExists('tenant_extensions'); Schema::dropIfExists('extension_versions'); Schema::dropIfExists('extension_packages'); Schema::dropIfExists('extension_publishers'); }
};
