<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('integration_connectors', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('key',80); $t->string('name'); $t->string('connector_type',30); $t->json('manifest'); $t->string('status',20)->default('disabled'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->unique(['tenant_id','key']); });
        Schema::create('integration_connections', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('connector_id'); $t->string('name'); $t->json('configuration')->nullable(); $t->text('encrypted_credentials')->nullable(); $t->string('status',20)->default('active'); $t->timestamp('credential_expires_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('connector_id')->references('id')->on('integration_connectors')->cascadeOnDelete(); });
        Schema::create('integration_mappings', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('connection_id')->index(); $t->string('name'); $t->string('source_format',20); $t->string('target_format',20); $t->json('mapping'); $t->json('validation_rules')->nullable(); $t->timestamps(); $t->foreign('connection_id')->references('id')->on('integration_connections')->cascadeOnDelete(); });
        Schema::create('integration_events', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('event_type',100); $t->string('subject_type',80)->nullable(); $t->string('subject_id',80)->nullable(); $t->json('payload'); $t->timestamp('occurred_at'); $t->timestamp('published_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->index(['event_type','published_at']); });
        Schema::create('webhook_subscriptions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('connection_id')->nullable(); $t->string('url'); $t->json('event_filters'); $t->string('secret_reference')->nullable(); $t->string('status',20)->default('active'); $t->unsignedInteger('max_retries')->default(3); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('connection_id')->references('id')->on('integration_connections')->nullOnDelete(); });
        Schema::create('webhook_deliveries', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('subscription_id')->index(); $t->uuid('event_id')->nullable(); $t->string('status',20); $t->unsignedInteger('attempt')->default(1); $t->unsignedSmallInteger('response_code')->nullable(); $t->text('response_body')->nullable(); $t->timestamp('delivered_at')->nullable(); $t->timestamp('next_retry_at')->nullable(); $t->timestamps(); $t->foreign('subscription_id')->references('id')->on('webhook_subscriptions')->cascadeOnDelete(); $t->foreign('event_id')->references('id')->on('integration_events')->nullOnDelete(); });
        Schema::create('integration_sync_runs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('connection_id')->index(); $t->string('sync_type',20); $t->string('status',20); $t->unsignedInteger('processed')->default(0); $t->unsignedInteger('failed')->default(0); $t->json('checkpoint')->nullable(); $t->text('error_message')->nullable(); $t->timestamp('started_at'); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('connection_id')->references('id')->on('integration_connections')->cascadeOnDelete(); });
        Schema::create('integration_dead_letters', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('connection_id')->nullable(); $t->string('job_type',100); $t->json('payload'); $t->text('error_message'); $t->unsignedInteger('attempts'); $t->timestamp('failed_at'); $t->timestamp('replayed_at')->nullable(); $t->timestamps(); $t->foreign('connection_id')->references('id')->on('integration_connections')->nullOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('integration_dead_letters'); Schema::dropIfExists('integration_sync_runs'); Schema::dropIfExists('webhook_deliveries'); Schema::dropIfExists('webhook_subscriptions'); Schema::dropIfExists('integration_events'); Schema::dropIfExists('integration_mappings'); Schema::dropIfExists('integration_connections'); Schema::dropIfExists('integration_connectors'); }
};
