<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('metadata_entities', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('key',80); $t->string('label'); $t->string('module',80)->nullable(); $t->string('status',20)->default('draft'); $t->unsignedInteger('version')->default(1); $t->json('settings')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->unique(['tenant_id','key','version']); });
        Schema::create('metadata_fields', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('entity_id')->index(); $t->string('key',80); $t->string('label'); $t->string('field_type',40); $t->unsignedInteger('sort_order')->default(0); $t->json('configuration')->nullable(); $t->json('validation_rules')->nullable(); $t->json('visibility_expression')->nullable(); $t->json('formula')->nullable(); $t->timestamps(); $t->foreign('entity_id')->references('id')->on('metadata_entities')->cascadeOnDelete(); $t->unique(['entity_id','key']); });
        Schema::create('metadata_forms', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('entity_id')->index(); $t->string('key',80); $t->string('name'); $t->string('status',20)->default('draft'); $t->json('layout'); $t->json('actions')->nullable(); $t->timestamps(); $t->foreign('entity_id')->references('id')->on('metadata_entities')->cascadeOnDelete(); $t->unique(['entity_id','key']); });
        Schema::create('metadata_records', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('entity_id')->index(); $t->json('data'); $t->string('status',20)->default('active'); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->softDeletes(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('entity_id')->references('id')->on('metadata_entities')->cascadeOnDelete(); });
        Schema::create('metadata_relationships', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('source_entity_id'); $t->uuid('target_entity_id'); $t->string('relationship_type',30); $t->string('source_field')->nullable(); $t->string('target_field')->nullable(); $t->json('configuration')->nullable(); $t->timestamps(); $t->foreign('source_entity_id')->references('id')->on('metadata_entities')->cascadeOnDelete(); $t->foreign('target_entity_id')->references('id')->on('metadata_entities')->cascadeOnDelete(); });
        Schema::create('metadata_bindings', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->uuid('entity_id')->nullable(); $t->string('binding_type',40); $t->string('event',80)->nullable(); $t->json('configuration'); $t->uuid('workflow_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->foreign('entity_id')->references('id')->on('metadata_entities')->nullOnDelete(); $t->foreign('workflow_id')->references('id')->on('workflows')->nullOnDelete(); });
        Schema::create('metadata_artifacts', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('artifact_type',40); $t->string('key',80); $t->string('status',20)->default('draft'); $t->unsignedInteger('version')->default(1); $t->json('definition'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->unique(['tenant_id','artifact_type','key','version']); });
        Schema::create('metadata_audits', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('subject_type',80); $t->string('subject_id',80); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('action',40); $t->json('old_values')->nullable(); $t->json('new_values')->nullable(); $t->timestamp('occurred_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('metadata_audits'); Schema::dropIfExists('metadata_artifacts'); Schema::dropIfExists('metadata_bindings'); Schema::dropIfExists('metadata_relationships'); Schema::dropIfExists('metadata_records'); Schema::dropIfExists('metadata_forms'); Schema::dropIfExists('metadata_fields'); Schema::dropIfExists('metadata_entities'); }
};
