<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('divisions', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('company_id')->index(); $t->uuid('business_unit_id')->nullable()->index(); $t->uuid('parent_id')->nullable()->index(); $t->string('code', 80); $t->string('name'); $t->text('description')->nullable(); $t->uuid('head_position_id')->nullable()->index(); $t->string('status', 20)->default('active'); $t->date('effective_from')->nullable(); $t->date('effective_to')->nullable(); $t->unsignedInteger('version')->default(1); $t->timestamps(); $t->softDeletes(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete(); $t->unique(['tenant_id','code']); });
        foreach (['profit_centers', 'job_families'] as $table) Schema::create($table, function (Blueprint $t) use ($table): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); if ($table === 'profit_centers') { $t->uuid('company_id')->index(); $t->uuid('parent_id')->nullable()->index(); } $t->string('code', 80); $t->string('name'); $t->text('description')->nullable(); $t->string('status', 20)->default('active'); $t->timestamps(); $t->softDeletes(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['tenant_id','code']); });
        Schema::create('organization_job_definitions', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('job_family_id')->nullable()->index(); $t->string('job_code', 80); $t->string('title'); $t->text('description')->nullable(); $t->json('skills')->nullable(); $t->unsignedSmallInteger('minimum_experience')->nullable(); $t->string('status', 20)->default('active'); $t->date('effective_from')->nullable(); $t->date('effective_to')->nullable(); $t->timestamps(); $t->softDeletes(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('job_family_id')->references('id')->on('job_families')->nullOnDelete(); $t->unique(['tenant_id','job_code']); });
        Schema::table('positions', function (Blueprint $t): void { $t->uuid('company_id')->nullable()->index(); $t->uuid('division_id')->nullable()->index(); $t->uuid('team_id')->nullable()->index(); $t->uuid('location_id')->nullable()->index(); $t->uuid('profit_center_id')->nullable()->index(); $t->uuid('job_id')->nullable()->index(); $t->uuid('parent_position_id')->nullable()->index(); $t->string('position_code', 80)->nullable(); $t->string('title_override')->nullable(); $t->unsignedInteger('headcount')->default(1); $t->unsignedInteger('filled_headcount')->default(0); $t->date('effective_from')->nullable(); $t->date('effective_to')->nullable(); $t->unsignedInteger('version')->default(1); });
        Schema::create('organization_assignments', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('subject_type', 120); $t->string('subject_id', 80); $t->uuid('position_id')->nullable()->index(); $t->uuid('company_id')->nullable()->index(); $t->uuid('department_id')->nullable()->index(); $t->uuid('branch_id')->nullable()->index(); $t->date('effective_from'); $t->date('effective_to')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('position_id')->references('id')->on('positions')->nullOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('organization_assignments'); Schema::table('positions', fn (Blueprint $t) => $t->dropColumn(['company_id','division_id','team_id','location_id','profit_center_id','job_id','parent_position_id','position_code','title_override','headcount','filled_headcount','effective_from','effective_to','version'])); foreach (['organization_job_definitions','job_families','profit_centers','divisions'] as $table) Schema::dropIfExists($table); }
};
