<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('legacy_critical_position_profiles', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('position_id')->unique(); $t->string('vacancy_risk',20); $t->string('business_impact',20); $t->unsignedInteger('replacement_time_days')->nullable(); $t->decimal('replacement_cost',15,2)->nullable(); $t->json('risk_factors')->nullable(); $t->timestamps(); $t->foreign('position_id')->references('id')->on('positions')->cascadeOnDelete(); });
        Schema::create('legacy_position_successors', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('position_id')->index(); $t->uuid('employee_id'); $t->string('successor_type',20); $t->string('readiness_level',30); $t->date('readiness_date')->nullable(); $t->decimal('confidence_score',5,2)->nullable(); $t->string('risk_level',20)->nullable(); $t->json('notes')->nullable(); $t->timestamps(); $t->foreign('position_id')->references('id')->on('positions')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->restrictOnDelete(); $t->unique(['position_id','employee_id']); });
        Schema::create('legacy_talent_pools', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->text('description')->nullable(); $t->json('criteria')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('legacy_talent_pool_members', function (Blueprint $t) { $t->uuid('talent_pool_id'); $t->uuid('employee_id'); $t->timestamp('added_at'); $t->primary(['talent_pool_id','employee_id']); $t->foreign('talent_pool_id')->references('id')->on('legacy_talent_pools')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); });
        Schema::create('legacy_career_paths', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->json('positions'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('legacy_talent_reviews', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->unsignedTinyInteger('performance_score'); $t->unsignedTinyInteger('potential_score'); $t->string('nine_box',20); $t->json('competency_scores')->nullable(); $t->string('flight_risk',20)->nullable(); $t->string('retirement_risk',20)->nullable(); $t->text('comments')->nullable(); $t->string('status',20)->default('draft'); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('legacy_development_plans', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('employee_id')->index(); $t->uuid('talent_review_id')->nullable(); $t->json('actions'); $t->string('status',20)->default('active'); $t->timestamps(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('talent_review_id')->references('id')->on('legacy_talent_reviews')->nullOnDelete(); });
        Schema::create('legacy_mentorships', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('mentor_employee_id'); $t->uuid('mentee_employee_id'); $t->json('goals')->nullable(); $t->string('status',20)->default('active'); $t->date('starts_on'); $t->date('ends_on')->nullable(); $t->timestamps(); $t->foreign('mentor_employee_id')->references('id')->on('employees')->restrictOnDelete(); $t->foreign('mentee_employee_id')->references('id')->on('employees')->restrictOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('legacy_mentorships'); Schema::dropIfExists('legacy_development_plans'); Schema::dropIfExists('legacy_talent_reviews'); Schema::dropIfExists('legacy_career_paths'); Schema::dropIfExists('legacy_talent_pool_members'); Schema::dropIfExists('legacy_talent_pools'); Schema::dropIfExists('legacy_position_successors'); Schema::dropIfExists('legacy_critical_position_profiles'); }
};
