<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('payroll_groups', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('frequency',20); $t->string('currency',3); $t->json('assignment_rules')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('payroll_components', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('code',50); $t->string('name'); $t->string('component_type',20); $t->string('calculation_type',20); $t->decimal('default_value',15,4)->nullable(); $t->string('formula')->nullable(); $t->json('rules')->nullable(); $t->date('effective_from'); $t->date('effective_to')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['tenant_id','code','effective_from']); });
        Schema::create('salary_structures', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->uuid('payroll_group_id')->nullable(); $t->json('components'); $t->date('effective_from'); $t->date('effective_to')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('payroll_group_id')->references('id')->on('payroll_groups')->nullOnDelete(); });
        Schema::create('payroll_periods', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('payroll_group_id')->nullable(); $t->date('start_date'); $t->date('end_date'); $t->date('cutoff_date')->nullable(); $t->date('payment_date')->nullable(); $t->string('status',20)->default('draft'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('payroll_group_id')->references('id')->on('payroll_groups')->nullOnDelete(); });
        Schema::create('payroll_runs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('payroll_period_id'); $t->string('status',20)->default('draft'); $t->uuid('workflow_instance_id')->nullable(); $t->decimal('gross_total',18,2)->default(0); $t->decimal('deduction_total',18,2)->default(0); $t->decimal('net_total',18,2)->default(0); $t->timestamp('locked_at')->nullable(); $t->timestamp('posted_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('payroll_period_id')->references('id')->on('payroll_periods')->restrictOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('payroll_entries', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('payroll_run_id')->index(); $t->uuid('employee_id')->index(); $t->decimal('gross_salary',18,2)->default(0); $t->decimal('deductions',18,2)->default(0); $t->decimal('net_salary',18,2)->default(0); $t->json('attendance_summary')->nullable(); $t->json('leave_summary')->nullable(); $t->json('components'); $t->timestamps(); $t->foreign('payroll_run_id')->references('id')->on('payroll_runs')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->restrictOnDelete(); $t->unique(['payroll_run_id','employee_id']); });
        Schema::create('employee_loans', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id')->index(); $t->string('loan_type',40); $t->decimal('principal',15,2); $t->decimal('outstanding',15,2); $t->decimal('installment_amount',15,2); $t->date('start_date'); $t->date('end_date')->nullable(); $t->string('status',20)->default('active'); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('employee_loans'); Schema::dropIfExists('payroll_entries'); Schema::dropIfExists('payroll_runs'); Schema::dropIfExists('payroll_periods'); Schema::dropIfExists('salary_structures'); Schema::dropIfExists('payroll_components'); Schema::dropIfExists('payroll_groups'); }
};
