<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('service_catalogs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('parent_id')->nullable(); $t->string('name'); $t->json('request_fields')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('parent_id')->references('id')->on('service_catalogs')->nullOnDelete(); });
        Schema::create('service_queues', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->uuid('department_id')->nullable(); $t->string('assignment_strategy',30)->default('manual'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('department_id')->references('id')->on('departments')->nullOnDelete(); });
        Schema::create('sla_policies', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('priority',20); $t->unsignedInteger('response_minutes'); $t->unsignedInteger('resolution_minutes'); $t->json('business_hours')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('service_tickets', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('ticket_number',50); $t->uuid('catalog_id')->nullable(); $t->uuid('queue_id')->nullable(); $t->uuid('requester_employee_id'); $t->uuid('assignee_employee_id')->nullable(); $t->uuid('asset_id')->nullable(); $t->uuid('sla_policy_id')->nullable(); $t->string('ticket_type',30); $t->string('priority',20); $t->string('status',30)->default('new'); $t->string('subject'); $t->longText('description')->nullable(); $t->timestamp('respond_by_at')->nullable(); $t->timestamp('resolve_by_at')->nullable(); $t->timestamp('resolved_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('catalog_id')->references('id')->on('service_catalogs')->nullOnDelete(); $t->foreign('queue_id')->references('id')->on('service_queues')->nullOnDelete(); $t->foreign('requester_employee_id')->references('id')->on('employees')->restrictOnDelete(); $t->foreign('assignee_employee_id')->references('id')->on('employees')->nullOnDelete(); $t->foreign('asset_id')->references('id')->on('assets')->nullOnDelete(); $t->foreign('sla_policy_id')->references('id')->on('sla_policies')->nullOnDelete(); $t->unique(['tenant_id','ticket_number']); });
        Schema::create('ticket_messages', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('ticket_id')->index(); $t->uuid('author_employee_id')->nullable(); $t->boolean('is_internal')->default(false); $t->longText('body'); $t->json('document_ids')->nullable(); $t->timestamps(); $t->foreign('ticket_id')->references('id')->on('service_tickets')->cascadeOnDelete(); $t->foreign('author_employee_id')->references('id')->on('employees')->nullOnDelete(); });
        Schema::create('knowledge_articles', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('catalog_id')->nullable(); $t->string('title'); $t->longText('body'); $t->json('document_ids')->nullable(); $t->string('status',20)->default('draft'); $t->unsignedInteger('version')->default(1); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('catalog_id')->references('id')->on('service_catalogs')->nullOnDelete(); });
        Schema::create('ticket_satisfaction', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('ticket_id')->unique(); $t->unsignedTinyInteger('rating'); $t->text('comments')->nullable(); $t->timestamps(); $t->foreign('ticket_id')->references('id')->on('service_tickets')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('ticket_satisfaction'); Schema::dropIfExists('knowledge_articles'); Schema::dropIfExists('ticket_messages'); Schema::dropIfExists('service_tickets'); Schema::dropIfExists('sla_policies'); Schema::dropIfExists('service_queues'); Schema::dropIfExists('service_catalogs'); }
};
