<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('tenant_environments', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('environment',20); $t->string('status',20)->default('provisioning'); $t->string('platform_version')->nullable(); $t->json('configuration')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['tenant_id','environment']); });
        Schema::create('tenant_provisioning_runs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('tenant_type',20); $t->string('status',20); $t->json('options')->nullable(); $t->json('result')->nullable(); $t->text('error_message')->nullable(); $t->foreignId('requested_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('started_at'); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); });
        Schema::create('implementation_projects', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('status',20)->default('planning'); $t->date('target_go_live')->nullable(); $t->json('milestones')->nullable(); $t->json('risks')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('implementation_tasks', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('project_id')->index(); $t->string('stage',50); $t->string('title'); $t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('status',20)->default('pending'); $t->date('due_date')->nullable(); $t->json('dependencies')->nullable(); $t->json('metadata')->nullable(); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('project_id')->references('id')->on('implementation_projects')->cascadeOnDelete(); });
        Schema::create('tenant_data_migrations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('data_domain',40); $t->string('status',20); $t->json('mapping')->nullable(); $t->json('validation_summary')->nullable(); $t->json('error_report')->nullable(); $t->unsignedInteger('processed')->default(0); $t->unsignedInteger('failed')->default(0); $t->timestamp('started_at')->nullable(); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('tenant_readiness_assessments', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('assessment_type',30); $t->decimal('score',5,2); $t->json('checks'); $t->timestamp('assessed_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('tenant_subscriptions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('plan'); $t->string('status',20); $t->unsignedInteger('seat_limit')->nullable(); $t->json('module_licenses')->nullable(); $t->timestamp('trial_ends_at')->nullable(); $t->timestamp('starts_at'); $t->timestamp('ends_at')->nullable(); $t->timestamp('grace_ends_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('tenant_health_snapshots', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->decimal('health_score',5,2); $t->json('factors'); $t->timestamp('snapshotted_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('tenant_upgrade_runs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_environment_id')->index(); $t->string('from_version'); $t->string('to_version'); $t->string('status',20); $t->json('compatibility_checks')->nullable(); $t->json('migration_result')->nullable(); $t->timestamp('started_at')->nullable(); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('tenant_environment_id')->references('id')->on('tenant_environments')->cascadeOnDelete(); });
        Schema::create('tenant_lifecycle_audits', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('action',80); $t->json('metadata')->nullable(); $t->timestamp('occurred_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('tenant_lifecycle_audits'); Schema::dropIfExists('tenant_upgrade_runs'); Schema::dropIfExists('tenant_health_snapshots'); Schema::dropIfExists('tenant_subscriptions'); Schema::dropIfExists('tenant_readiness_assessments'); Schema::dropIfExists('tenant_data_migrations'); Schema::dropIfExists('implementation_tasks'); Schema::dropIfExists('implementation_projects'); Schema::dropIfExists('tenant_provisioning_runs'); Schema::dropIfExists('tenant_environments'); }
};
