<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        if (! Schema::hasTable('training_categories')) {
            Schema::create('training_categories', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['tenant_id','name']); });
        }
        Schema::create('courses', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('category_id')->nullable(); $t->string('code',50); $t->string('name'); $t->longText('description')->nullable(); $t->string('delivery_type',30); $t->string('level',30)->nullable(); $t->unsignedInteger('duration_minutes')->nullable(); $t->decimal('credit_hours',6,2)->nullable(); $t->decimal('cost',15,2)->nullable(); $t->unsignedInteger('passing_score')->nullable(); $t->unsignedInteger('expiry_months')->nullable(); $t->unsignedInteger('version')->default(1); $t->boolean('is_mandatory')->default(false); $t->string('status',20)->default('draft'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('category_id')->references('id')->on('training_categories')->nullOnDelete(); $t->unique(['tenant_id','code','version']); });
        Schema::create('course_contents', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('course_id')->index(); $t->uuid('document_id')->nullable(); $t->string('content_type',30); $t->string('title'); $t->string('external_url')->nullable(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->foreign('course_id')->references('id')->on('courses')->cascadeOnDelete(); $t->foreign('document_id')->references('id')->on('documents')->nullOnDelete(); });
        Schema::create('legacy_learning_paths', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->json('assignment_rules')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('legacy_learning_path_courses', function (Blueprint $t) { $t->uuid('learning_path_id'); $t->uuid('course_id'); $t->unsignedInteger('sort_order'); $t->primary(['learning_path_id','course_id']); $t->foreign('learning_path_id')->references('id')->on('legacy_learning_paths')->cascadeOnDelete(); $t->foreign('course_id')->references('id')->on('courses')->cascadeOnDelete(); });
        Schema::create('training_sessions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('course_id')->index(); $t->uuid('instructor_employee_id')->nullable(); $t->string('delivery_mode',20); $t->string('location')->nullable(); $t->string('meeting_url')->nullable(); $t->unsignedInteger('capacity')->nullable(); $t->timestamp('starts_at'); $t->timestamp('ends_at'); $t->timestamps(); $t->foreign('course_id')->references('id')->on('courses')->cascadeOnDelete(); $t->foreign('instructor_employee_id')->references('id')->on('employees')->nullOnDelete(); });
        Schema::create('course_enrollments', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->uuid('course_id'); $t->uuid('session_id')->nullable(); $t->string('status',20)->default('assigned'); $t->unsignedInteger('progress')->default(0); $t->unsignedInteger('time_spent_minutes')->default(0); $t->timestamp('completed_at')->nullable(); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('course_id')->references('id')->on('courses')->cascadeOnDelete(); $t->foreign('session_id')->references('id')->on('training_sessions')->nullOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); $t->unique(['employee_id','course_id','session_id']); });
        Schema::create('certifications', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->uuid('course_id')->nullable(); $t->uuid('document_id')->nullable(); $t->string('credential_number')->nullable(); $t->date('issued_at'); $t->date('expires_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('course_id')->references('id')->on('courses')->nullOnDelete(); $t->foreign('document_id')->references('id')->on('documents')->nullOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('certifications'); Schema::dropIfExists('course_enrollments'); Schema::dropIfExists('training_sessions'); Schema::dropIfExists('legacy_learning_path_courses'); Schema::dropIfExists('legacy_learning_paths'); Schema::dropIfExists('course_contents'); Schema::dropIfExists('courses'); Schema::dropIfExists('training_categories'); }
};
