<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('performance_cycles', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('uuid')->unique(); $t->string('name'); $t->text('description')->nullable(); $t->string('cycle_type', 30); $t->date('start_date'); $t->date('end_date'); $t->date('self_review_start')->nullable(); $t->date('self_review_end')->nullable(); $t->date('manager_review_start')->nullable(); $t->date('manager_review_end')->nullable(); $t->date('calibration_start')->nullable(); $t->date('calibration_end')->nullable(); $t->date('finalization_date')->nullable(); $t->string('status', 30)->default('draft'); $t->unsignedInteger('version')->default(1); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->softDeletes(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->index(['tenant_id', 'status']); });
        Schema::create('performance_cycle_configurations', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('cycle_id')->unique(); $t->decimal('goal_weight', 5, 2)->default(100); $t->decimal('competency_weight', 5, 2)->default(0); $t->decimal('feedback_weight', 5, 2)->default(0); $t->boolean('self_assessment_enabled')->default(true); $t->boolean('manager_assessment_enabled')->default(true); $t->boolean('feedback_360_enabled')->default(false); $t->boolean('calibration_enabled')->default(false); $t->boolean('pip_enabled')->default(false); $t->boolean('employee_acknowledgement_required')->default(false); $t->unsignedInteger('minimum_response_count')->default(3); $t->json('eligibility_rules')->nullable(); $t->json('feedback_groups')->nullable(); $t->json('formula_components')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('cycle_id')->references('id')->on('performance_cycles')->cascadeOnDelete(); });
        Schema::create('performance_cycle_participants', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('cycle_id')->index(); $t->uuid('employee_id')->index(); $t->uuid('manager_id')->nullable(); $t->string('status', 30)->default('eligible'); $t->date('eligible_from')->nullable(); $t->date('eligible_to')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('cycle_id')->references('id')->on('performance_cycles')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('manager_id')->references('id')->on('employees')->nullOnDelete(); $t->unique(['cycle_id', 'employee_id']); });
        Schema::create('performance_goals', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('uuid')->unique(); $t->uuid('cycle_id')->index(); $t->uuid('employee_id')->nullable()->index(); $t->uuid('parent_goal_id')->nullable()->index(); $t->string('owner_type', 30); $t->string('title'); $t->text('description')->nullable(); $t->string('goal_type', 30); $t->string('measurement_type', 30)->default('manual'); $t->decimal('weight', 5, 2)->default(0); $t->decimal('target_value', 18, 4)->nullable(); $t->decimal('current_value', 18, 4)->nullable(); $t->string('unit', 30)->nullable(); $t->date('start_date')->nullable(); $t->date('due_date')->nullable(); $t->string('status', 30)->default('draft'); $t->decimal('progress_percentage', 5, 2)->default(0); $t->string('priority', 20)->default('medium'); $t->unsignedInteger('version')->default(1); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->softDeletes(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('cycle_id')->references('id')->on('performance_cycles')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->nullOnDelete(); $t->foreign('parent_goal_id')->references('id')->on('performance_goals')->nullOnDelete(); $t->index(['cycle_id', 'status']); });
        Schema::create('performance_goal_contributors', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('goal_id')->index(); $t->uuid('employee_id')->index(); $t->string('role', 20); $t->decimal('weight', 5, 2)->nullable(); $t->timestamps(); $t->foreign('goal_id')->references('id')->on('performance_goals')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->unique(['goal_id', 'employee_id']); });
        Schema::create('performance_goal_progress', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('goal_id')->index(); $t->uuid('recorded_by')->nullable(); $t->timestamp('recorded_at'); $t->decimal('previous_value', 18, 4)->nullable(); $t->decimal('new_value', 18, 4)->nullable(); $t->decimal('progress_percentage', 5, 2); $t->text('comment')->nullable(); $t->string('source', 30); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('goal_id')->references('id')->on('performance_goals')->cascadeOnDelete(); });
        Schema::create('performance_goal_milestones', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('goal_id')->index(); $t->string('title'); $t->text('description')->nullable(); $t->date('due_date')->nullable(); $t->decimal('weight', 5, 2)->default(0); $t->string('status', 20)->default('pending'); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('goal_id')->references('id')->on('performance_goals')->cascadeOnDelete(); });
        Schema::create('performance_goal_comments', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('goal_id')->index(); $t->uuid('employee_id')->nullable(); $t->text('comment'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('goal_id')->references('id')->on('performance_goals')->cascadeOnDelete(); });
        Schema::create('performance_goal_change_requests', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('goal_id')->index(); $t->uuid('requested_by'); $t->json('requested_changes'); $t->text('reason'); $t->string('status', 20)->default('pending'); $t->uuid('reviewed_by')->nullable(); $t->timestamp('reviewed_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('goal_id')->references('id')->on('performance_goals')->cascadeOnDelete(); });
        Schema::create('performance_goal_templates', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('title'); $t->text('description')->nullable(); $t->string('goal_type', 30); $t->decimal('default_weight', 5, 2)->nullable(); $t->string('measurement_type', 30); $t->string('suggested_target')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('performance_checkins', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('cycle_id')->index(); $t->uuid('employee_id')->index(); $t->uuid('manager_id')->nullable(); $t->timestamp('scheduled_at'); $t->timestamp('completed_at')->nullable(); $t->text('summary')->nullable(); $t->text('employee_comment')->nullable(); $t->text('manager_comment')->nullable(); $t->json('agenda_items')->nullable(); $t->string('status', 20)->default('scheduled'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('cycle_id')->references('id')->on('performance_cycles')->cascadeOnDelete(); });
        Schema::create('performance_reviews', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('uuid')->unique(); $t->uuid('tenant_id')->index(); $t->uuid('cycle_id')->index(); $t->uuid('employee_id')->index(); $t->uuid('reviewer_id')->nullable(); $t->string('review_type', 20); $t->string('status', 30)->default('draft'); $t->decimal('overall_rating', 8, 4)->nullable(); $t->decimal('calculated_rating', 8, 4)->nullable(); $t->decimal('final_rating', 8, 4)->nullable(); $t->text('summary')->nullable(); $t->timestamp('submitted_at')->nullable(); $t->timestamp('finalized_at')->nullable(); $t->unsignedInteger('version')->default(1); $t->timestamps(); $t->softDeletes(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('cycle_id')->references('id')->on('performance_cycles')->cascadeOnDelete(); $t->unique(['cycle_id', 'employee_id', 'review_type']); });
        Schema::create('performance_review_versions', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('review_id')->index(); $t->unsignedInteger('version'); $t->json('snapshot'); $t->uuid('created_by')->nullable(); $t->timestamps(); $t->foreign('review_id')->references('id')->on('performance_reviews')->cascadeOnDelete(); $t->unique(['review_id', 'version']); });
        Schema::create('performance_self_assessments', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('review_id')->unique(); $t->json('goal_assessment')->nullable(); $t->json('competency_assessment')->nullable(); $t->text('achievements')->nullable(); $t->text('challenges')->nullable(); $t->text('development')->nullable(); $t->decimal('overall_self_rating', 8, 4)->nullable(); $t->text('comments')->nullable(); $t->timestamp('submitted_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('review_id')->references('id')->on('performance_reviews')->cascadeOnDelete(); });
        Schema::create('performance_feedback_requests', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('cycle_id')->index(); $t->uuid('employee_id')->index(); $t->uuid('requested_from_employee_id')->nullable(); $t->uuid('requested_by')->nullable(); $t->string('relationship_type', 30); $t->boolean('feedback_identity_hidden')->default(false); $t->string('status', 20)->default('pending'); $t->timestamp('due_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('performance_feedback_responses', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('request_id')->unique(); $t->decimal('rating', 8, 4)->nullable(); $t->text('response')->nullable(); $t->timestamp('submitted_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('request_id')->references('id')->on('performance_feedback_requests')->cascadeOnDelete(); });
        Schema::create('competency_frameworks', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->text('description')->nullable(); $t->string('status', 20)->default('draft'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('competency_categories', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('framework_id')->index(); $t->string('name'); $t->text('description')->nullable(); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->foreign('framework_id')->references('id')->on('competency_frameworks')->cascadeOnDelete(); });
        Schema::create('competencies', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('category_id')->nullable()->index(); $t->string('name'); $t->text('description')->nullable(); $t->string('status', 20)->default('active'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('category_id')->references('id')->on('competency_categories')->nullOnDelete(); });
        Schema::create('competency_levels', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('competency_id')->index(); $t->unsignedSmallInteger('level'); $t->string('label'); $t->text('description')->nullable(); $t->timestamps(); $t->foreign('competency_id')->references('id')->on('competencies')->cascadeOnDelete(); $t->unique(['competency_id', 'level']); });
        Schema::create('performance_competency_assignments', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('competency_id')->index(); $t->string('assignable_type', 40); $t->uuid('assignable_id'); $t->uuid('cycle_id')->nullable(); $t->decimal('weight', 5, 2)->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('performance_competency_assessments', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('review_id')->index(); $t->uuid('competency_id')->index(); $t->decimal('rating', 8, 4); $t->text('comment')->nullable(); $t->text('evidence')->nullable(); $t->timestamps(); $t->foreign('review_id')->references('id')->on('performance_reviews')->cascadeOnDelete(); $t->foreign('competency_id')->references('id')->on('competencies')->cascadeOnDelete(); $t->unique(['review_id', 'competency_id'], 'perf_comp_assess_rev_comp_uq'); });
        Schema::create('performance_rating_scales', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('rating_type', 20); $t->boolean('is_default')->default(false); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('performance_rating_scale_items', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('rating_scale_id')->index(); $t->decimal('value', 8, 4); $t->string('label'); $t->text('description')->nullable(); $t->decimal('min_score', 8, 4)->nullable(); $t->decimal('max_score', 8, 4)->nullable(); $t->timestamps(); $t->foreign('rating_scale_id')->references('id')->on('performance_rating_scales')->cascadeOnDelete(); $t->unique(['rating_scale_id', 'value']); });
        Schema::create('performance_calibration_sessions', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('cycle_id')->index(); $t->string('name'); $t->string('status', 20)->default('draft'); $t->timestamp('started_at')->nullable(); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('cycle_id')->references('id')->on('performance_cycles')->cascadeOnDelete(); });
        Schema::create('performance_calibration_records', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('session_id')->index(); $t->uuid('employee_id')->index(); $t->decimal('calculated_rating', 8, 4)->nullable(); $t->decimal('proposed_rating', 8, 4)->nullable(); $t->decimal('final_rating', 8, 4)->nullable(); $t->text('change_reason')->nullable(); $t->uuid('changed_by')->nullable(); $t->timestamp('changed_at')->nullable(); $t->timestamps(); $t->foreign('session_id')->references('id')->on('performance_calibration_sessions')->cascadeOnDelete(); $t->unique(['session_id', 'employee_id']); });
        Schema::create('performance_final_outcomes', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('cycle_id')->index(); $t->uuid('employee_id')->index(); $t->decimal('final_rating', 8, 4); $t->decimal('final_score', 8, 4)->nullable(); $t->text('summary')->nullable(); $t->text('strengths')->nullable(); $t->text('development_areas')->nullable(); $t->uuid('finalized_by')->nullable(); $t->timestamp('finalized_at'); $t->timestamp('employee_acknowledged_at')->nullable(); $t->text('employee_comment')->nullable(); $t->string('acknowledgement_status', 30)->default('pending'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['cycle_id', 'employee_id']); });
        Schema::create('performance_review_appeals', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('review_id')->index(); $t->uuid('employee_id')->index(); $t->text('reason'); $t->timestamp('submitted_at'); $t->string('status', 20)->default('submitted'); $t->text('resolution')->nullable(); $t->uuid('resolved_by')->nullable(); $t->timestamp('resolved_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        foreach (['performance_development_plans', 'performance_improvement_plans'] as $table) { Schema::create($table, function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id')->index(); $t->uuid('cycle_id')->nullable(); $t->string('status', 30)->default('draft'); $t->text('summary')->nullable(); $t->json('details')->nullable(); $t->date('start_date')->nullable(); $t->date('end_date')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); }); }
        foreach (['performance_development_actions' => 'performance_development_plans', 'performance_improvement_plan_actions' => 'performance_improvement_plans'] as $table => $parent) { Schema::create($table, function (Blueprint $t) use ($parent): void { $t->uuid('id')->primary(); $t->uuid('plan_id')->index(); $t->string('title'); $t->text('description')->nullable(); $t->uuid('owner_id')->nullable(); $t->date('due_date')->nullable(); $t->string('status', 20)->default('planned'); $t->decimal('completion_percentage', 5, 2)->default(0); $t->timestamps(); $t->foreign('plan_id')->references('id')->on($parent)->cascadeOnDelete(); }); }
        Schema::create('performance_recognitions', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id')->index(); $t->uuid('recognized_by')->nullable(); $t->string('recognition_type', 30); $t->string('title'); $t->text('message')->nullable(); $t->string('status', 20)->default('submitted'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('performance_history', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id')->index(); $t->uuid('cycle_id')->nullable(); $t->string('event_type', 50); $t->json('snapshot'); $t->timestamp('recorded_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
    }
    public function down(): void { foreach (['performance_history','performance_recognitions','performance_improvement_plan_actions','performance_development_actions','performance_improvement_plans','performance_development_plans','performance_review_appeals','performance_final_outcomes','performance_calibration_records','performance_calibration_sessions','performance_rating_scale_items','performance_rating_scales','performance_competency_assessments','performance_competency_assignments','competency_levels','competencies','competency_categories','competency_frameworks','performance_feedback_responses','performance_feedback_requests','performance_self_assessments','performance_review_versions','performance_reviews','performance_checkins','performance_goal_templates','performance_goal_change_requests','performance_goal_comments','performance_goal_milestones','performance_goal_progress','performance_goal_contributors','performance_goals','performance_cycle_participants','performance_cycle_configurations','performance_cycles'] as $table) Schema::dropIfExists($table); }
};
