<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('permission_groups', function (Blueprint $table): void { $table->uuid('tenant_id')->nullable()->index(); $table->string('module', 80)->default('platform'); $table->string('description')->nullable(); });
        Schema::table('permissions', function (Blueprint $table): void { $table->uuid('uuid')->nullable()->unique(); $table->uuid('tenant_id')->nullable()->index(); $table->string('module', 80)->default('platform')->index(); $table->string('resource', 100)->nullable(); $table->string('action', 60)->nullable(); $table->string('scope', 30)->default('tenant'); $table->string('description')->nullable(); $table->string('status', 20)->default('active')->index(); });
        Schema::table('roles', function (Blueprint $table): void { $table->uuid('uuid')->nullable()->unique(); $table->string('code', 100)->nullable(); $table->string('type', 20)->default('custom')->index(); $table->string('status', 20)->default('active')->index(); $table->unsignedSmallInteger('priority')->default(0); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->unique(['tenant_id', 'code']); });
        Schema::create('user_roles', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->uuid('tenant_id')->index(); $table->uuid('role_id')->index(); $table->string('scope', 30)->default('tenant'); $table->string('scope_id', 80)->nullable(); $table->timestamp('effective_from')->nullable(); $table->timestamp('effective_to')->nullable(); $table->boolean('is_primary')->default(false); $table->foreignId('assigned_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $table->foreign('role_id')->references('id')->on('roles')->cascadeOnDelete(); $table->unique(['user_id', 'tenant_id', 'role_id', 'scope', 'scope_id']); });
        Schema::create('role_inheritance', function (Blueprint $table): void { $table->uuid('role_id'); $table->uuid('parent_role_id'); $table->timestamps(); $table->primary(['role_id', 'parent_role_id']); $table->foreign('role_id')->references('id')->on('roles')->cascadeOnDelete(); $table->foreign('parent_role_id')->references('id')->on('roles')->cascadeOnDelete(); });
        Schema::create('role_scopes', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('role_id')->index(); $table->string('scope', 30); $table->string('scope_id', 80)->nullable(); $table->timestamps(); $table->foreign('role_id')->references('id')->on('roles')->cascadeOnDelete(); });
        Schema::create('permission_overrides', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('tenant_id')->index(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->foreignId('permission_id')->constrained()->cascadeOnDelete(); $table->string('effect', 10); $table->timestamp('effective_from')->nullable(); $table->timestamp('effective_to')->nullable(); $table->timestamps(); $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $table->unique(['tenant_id', 'user_id', 'permission_id']); });
        Schema::create('field_permissions', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('tenant_id')->nullable()->index(); $table->string('resource', 100); $table->string('field', 100); $table->string('access', 10)->default('hidden'); $table->timestamps(); $table->unique(['tenant_id', 'resource', 'field']); });
        Schema::create('role_field_permissions', function (Blueprint $table): void { $table->uuid('role_id'); $table->uuid('field_permission_id'); $table->string('access', 10)->default('full'); $table->timestamps(); $table->primary(['role_id', 'field_permission_id']); $table->foreign('role_id')->references('id')->on('roles')->cascadeOnDelete(); $table->foreign('field_permission_id')->references('id')->on('field_permissions')->cascadeOnDelete(); });
        Schema::create('approval_authorities', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('tenant_id')->index(); $table->uuid('role_id')->nullable()->index(); $table->string('transaction_type', 100); $table->string('scope', 30)->default('tenant'); $table->string('scope_id', 80)->nullable(); $table->decimal('minimum_amount', 18, 2)->default(0); $table->decimal('maximum_amount', 18, 2)->nullable(); $table->timestamp('effective_from')->nullable(); $table->timestamp('effective_to')->nullable(); $table->timestamps(); $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $table->foreign('role_id')->references('id')->on('roles')->nullOnDelete(); });
        Schema::create('delegations', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('tenant_id')->index(); $table->foreignId('delegator_id')->constrained('users')->cascadeOnDelete(); $table->foreignId('delegate_id')->constrained('users')->cascadeOnDelete(); $table->string('permission', 160)->nullable(); $table->string('approval_type', 100)->nullable(); $table->timestamp('starts_at'); $table->timestamp('ends_at'); $table->string('status', 20)->default('active'); $table->string('reason')->nullable(); $table->timestamps(); $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('authorization_audit_logs', function (Blueprint $table): void { $table->uuid('id')->primary(); $table->uuid('tenant_id')->nullable()->index(); $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $table->string('permission', 160); $table->boolean('allowed'); $table->string('reason', 255); $table->json('context')->nullable(); $table->timestamp('occurred_at'); $table->timestamps(); $table->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); });
    }

    public function down(): void
    {
        foreach (['authorization_audit_logs','delegations','approval_authorities','role_field_permissions','field_permissions','permission_overrides','role_scopes','role_inheritance','user_roles'] as $table) Schema::dropIfExists($table);
        Schema::table('roles', fn (Blueprint $table) => $table->dropColumn(['uuid','code','type','status','priority','created_by','updated_by']));
        Schema::table('permissions', fn (Blueprint $table) => $table->dropColumn(['uuid','tenant_id','module','resource','action','scope','description','status']));
        Schema::table('permission_groups', fn (Blueprint $table) => $table->dropColumn(['tenant_id','module','description']));
    }
};
