<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('asset_vendors', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('vendor_type',30); $t->json('contact_details')->nullable(); $t->json('sla')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('asset_inventories', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('category_id')->nullable(); $t->string('warehouse')->nullable(); $t->string('location')->nullable(); $t->unsignedInteger('available_quantity')->default(0); $t->unsignedInteger('reserved_quantity')->default(0); $t->unsignedInteger('minimum_stock')->default(0); $t->unsignedInteger('maximum_stock')->nullable(); $t->unsignedInteger('reorder_level')->default(0); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('category_id')->references('id')->on('asset_categories')->nullOnDelete(); });
        Schema::create('asset_transfers', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('asset_id')->index(); $t->string('from_type',30); $t->string('from_id',80)->nullable(); $t->string('to_type',30); $t->string('to_id',80)->nullable(); $t->string('status',20)->default('draft'); $t->uuid('workflow_instance_id')->nullable(); $t->timestamp('transferred_at')->nullable(); $t->timestamps(); $t->foreign('asset_id')->references('id')->on('assets')->cascadeOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('asset_reservations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('asset_id')->index(); $t->uuid('employee_id'); $t->timestamp('starts_at'); $t->timestamp('ends_at'); $t->string('status',20)->default('pending'); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('asset_id')->references('id')->on('assets')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('software_license_assignments', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('software_license_id')->index(); $t->uuid('employee_id')->nullable(); $t->uuid('asset_id')->nullable(); $t->timestamp('assigned_at'); $t->timestamp('revoked_at')->nullable(); $t->timestamps(); $t->foreign('software_license_id')->references('id')->on('software_licenses')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->nullOnDelete(); $t->foreign('asset_id')->references('id')->on('assets')->nullOnDelete(); });
        Schema::create('asset_audits', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('asset_id'); $t->foreignId('audited_by')->nullable()->constrained('users')->nullOnDelete(); $t->string('result',20); $t->text('notes')->nullable(); $t->json('evidence_document_ids')->nullable(); $t->timestamp('audited_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('asset_id')->references('id')->on('assets')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('asset_audits'); Schema::dropIfExists('software_license_assignments'); Schema::dropIfExists('asset_reservations'); Schema::dropIfExists('asset_transfers'); Schema::dropIfExists('asset_inventories'); Schema::dropIfExists('asset_vendors'); }
};
