<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('analytics_dimensions', function (Blueprint $t) { $t->bigIncrements('id'); $t->uuid('tenant_id')->index(); $t->string('dimension_type',50); $t->string('natural_key',80); $t->json('attributes'); $t->date('valid_from'); $t->date('valid_to')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->index(['tenant_id','dimension_type','natural_key']); });
        Schema::create('analytics_facts', function (Blueprint $t) { $t->bigIncrements('id'); $t->uuid('tenant_id')->index(); $t->string('fact_type',50); $t->date('fact_date')->index(); $t->string('subject_type',50)->nullable(); $t->string('subject_id',80)->nullable(); $t->json('dimensions')->nullable(); $t->json('measures'); $t->timestamp('source_updated_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->index(['tenant_id','fact_type','fact_date']); });
        Schema::create('analytics_snapshots', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('snapshot_type',50); $t->date('snapshot_date'); $t->json('payload'); $t->timestamp('calculated_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['tenant_id','snapshot_type','snapshot_date']); });
        Schema::create('kpi_definitions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('code',80); $t->string('name'); $t->string('category',50)->nullable(); $t->string('calculation_type',30); $t->json('definition'); $t->string('unit',30)->nullable(); $t->string('frequency',20); $t->boolean('is_active')->default(true); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->unique(['tenant_id','code']); });
        Schema::create('kpi_values', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('kpi_definition_id'); $t->date('period_start'); $t->date('period_end'); $t->decimal('value',20,6); $t->json('dimensions')->nullable(); $t->timestamp('calculated_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('kpi_definition_id')->references('id')->on('kpi_definitions')->cascadeOnDelete(); $t->index(['tenant_id','kpi_definition_id','period_end']); });
        Schema::create('analytics_etl_runs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('pipeline',80); $t->string('run_type',20); $t->string('status',20); $t->unsignedInteger('records_processed')->default(0); $t->json('checkpoint')->nullable(); $t->text('error_message')->nullable(); $t->timestamp('started_at'); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); });
        Schema::create('analytics_datasets', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('source_type',50); $t->json('definition'); $t->json('security_rules')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('analytics_dashboards', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('audience',50)->nullable(); $t->json('layout'); $t->json('security_rules')->nullable(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('analytics_reports', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('dataset_id')->nullable(); $t->string('name'); $t->json('definition'); $t->json('schedule')->nullable(); $t->json('delivery')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('dataset_id')->references('id')->on('analytics_datasets')->nullOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('analytics_reports'); Schema::dropIfExists('analytics_dashboards'); Schema::dropIfExists('analytics_datasets'); Schema::dropIfExists('analytics_etl_runs'); Schema::dropIfExists('kpi_values'); Schema::dropIfExists('kpi_definitions'); Schema::dropIfExists('analytics_snapshots'); Schema::dropIfExists('analytics_facts'); Schema::dropIfExists('analytics_dimensions'); }
};
