<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        if (! Schema::hasTable('compensation_bands')) {
            Schema::create('compensation_bands', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('code',50); $t->string('name'); $t->uuid('job_grade_id')->nullable(); $t->string('currency',3); $t->decimal('minimum',15,2); $t->decimal('midpoint',15,2); $t->decimal('maximum',15,2); $t->string('location')->nullable(); $t->date('effective_from'); $t->date('effective_to')->nullable(); $t->unsignedInteger('version')->default(1); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('job_grade_id')->references('id')->on('job_grades')->nullOnDelete(); $t->unique(['tenant_id','code','effective_from']); });
        }
        if (! Schema::hasTable('compensation_cycles')) { Schema::create('compensation_cycles', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('cycle_type',30); $t->date('starts_on'); $t->date('ends_on'); $t->date('effective_on'); $t->string('status',20)->default('draft'); $t->boolean('is_confidential')->default(false); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); }); }
        if (! Schema::hasTable('compensation_budgets')) { Schema::create('compensation_budgets', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('compensation_cycle_id')->index(); $t->string('scope_type',30); $t->string('scope_id',80); $t->decimal('allocated',18,2); $t->decimal('consumed',18,2)->default(0); $t->timestamps(); $t->foreign('compensation_cycle_id')->references('id')->on('compensation_cycles')->cascadeOnDelete(); }); }
        if (! Schema::hasTable('compensation_recommendations')) { Schema::create('compensation_recommendations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('compensation_cycle_id')->index(); $t->uuid('employee_id'); $t->decimal('current_base_salary',15,2); $t->decimal('recommended_base_salary',15,2); $t->decimal('increase_amount',15,2)->default(0); $t->decimal('increase_percentage',8,4)->default(0); $t->string('recommendation_type',30); $t->json('components')->nullable(); $t->text('justification')->nullable(); $t->string('status',20)->default('draft'); $t->timestamps(); $t->foreign('compensation_cycle_id')->references('id')->on('compensation_cycles')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->restrictOnDelete(); $t->unique(['compensation_cycle_id', 'employee_id'], 'comp_rec_cycle_emp_unique'); }); }
        Schema::create('bonus_allocations', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('compensation_cycle_id')->index(); $t->uuid('employee_id'); $t->string('bonus_type',30); $t->decimal('amount',15,2); $t->json('calculation_factors')->nullable(); $t->string('status',20)->default('draft'); $t->timestamps(); $t->foreign('compensation_cycle_id')->references('id')->on('compensation_cycles')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->restrictOnDelete(); });
        Schema::create('market_benchmarks', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('job_title'); $t->string('industry')->nullable(); $t->string('location')->nullable(); $t->string('currency',3); $t->decimal('percentile',5,2); $t->decimal('market_salary',15,2); $t->date('survey_date'); $t->json('metadata')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('total_rewards_statements', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->unsignedSmallInteger('year'); $t->json('components'); $t->decimal('total_employer_investment',18,2); $t->uuid('document_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('document_id')->references('id')->on('documents')->nullOnDelete(); $t->unique(['employee_id','year']); });
    }
    public function down(): void { Schema::dropIfExists('total_rewards_statements'); Schema::dropIfExists('market_benchmarks'); Schema::dropIfExists('bonus_allocations'); Schema::dropIfExists('compensation_recommendations'); Schema::dropIfExists('compensation_budgets'); Schema::dropIfExists('compensation_cycles'); Schema::dropIfExists('compensation_bands'); }
};
