<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('people', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('person_number', 80); $t->string('first_name'); $t->string('middle_name')->nullable(); $t->string('last_name'); $t->string('preferred_name')->nullable(); $t->string('display_name')->nullable(); $t->string('gender', 30)->nullable(); $t->date('date_of_birth')->nullable(); $t->string('nationality_code', 3)->nullable(); $t->string('status', 20)->default('active'); $t->unsignedInteger('version')->default(1); $t->timestamps(); $t->softDeletes(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['tenant_id','person_number']); });
        Schema::table('employees', function (Blueprint $t): void { $t->uuid('person_id')->nullable()->index(); $t->uuid('current_employment_id')->nullable()->index(); $t->uuid('current_position_id')->nullable()->index(); $t->uuid('current_manager_employee_id')->nullable()->index(); $t->date('original_hire_date')->nullable(); $t->date('termination_date')->nullable(); $t->boolean('portal_access')->default(false); $t->unsignedInteger('version')->default(1); $t->foreign('person_id')->references('id')->on('people')->nullOnDelete(); });
        Schema::create('employments', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id')->index(); $t->uuid('company_id')->index(); $t->uuid('employment_type_id')->nullable()->index(); $t->uuid('job_id')->nullable()->index(); $t->uuid('job_grade_id')->nullable()->index(); $t->uuid('position_id')->nullable()->index(); $t->uuid('department_id')->nullable()->index(); $t->uuid('manager_employee_id')->nullable()->index(); $t->string('employment_number', 80); $t->date('start_date'); $t->date('end_date')->nullable(); $t->string('status', 20)->default('draft'); $t->date('effective_from'); $t->date('effective_to')->nullable(); $t->unsignedInteger('version')->default(1); $t->timestamps(); $t->softDeletes(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('company_id')->references('id')->on('companies')->cascadeOnDelete(); $t->unique(['tenant_id','employment_number']); });
        Schema::create('employee_assignments', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id')->index(); $t->uuid('employment_id')->index(); $t->uuid('company_id')->nullable()->index(); $t->uuid('department_id')->nullable()->index(); $t->uuid('position_id')->nullable()->index(); $t->uuid('manager_employee_id')->nullable()->index(); $t->string('work_model', 30)->nullable(); $t->boolean('is_primary')->default(true); $t->date('effective_from'); $t->date('effective_to')->nullable(); $t->string('reason')->nullable(); $t->string('status', 20)->default('active'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('employment_id')->references('id')->on('employments')->cascadeOnDelete(); });
        Schema::create('employee_manager_relationships', function (Blueprint $t): void { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id')->index(); $t->uuid('manager_employee_id')->index(); $t->string('relationship_type', 30)->default('primary'); $t->boolean('is_primary')->default(false); $t->date('effective_from'); $t->date('effective_to')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('manager_employee_id')->references('id')->on('employees')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('employee_manager_relationships'); Schema::dropIfExists('employee_assignments'); Schema::dropIfExists('employments'); Schema::table('employees', fn (Blueprint $t) => $t->dropColumn(['person_id','current_employment_id','current_position_id','current_manager_employee_id','original_hire_date','termination_date','portal_access','version'])); Schema::dropIfExists('people'); }
};
