<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('health_check_definitions', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('key',80)->unique(); $t->string('name'); $t->string('check_type',40); $t->json('configuration')->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('health_check_results', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('definition_id')->index(); $t->uuid('tenant_id')->nullable()->index(); $t->string('status',20); $t->unsignedInteger('latency_ms')->nullable(); $t->json('details')->nullable(); $t->timestamp('checked_at'); $t->timestamps(); $t->foreign('definition_id')->references('id')->on('health_check_definitions')->cascadeOnDelete(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); });
        Schema::create('platform_metrics', function (Blueprint $t) { $t->bigIncrements('id'); $t->uuid('tenant_id')->nullable()->index(); $t->string('metric',100); $t->decimal('value',20,6); $t->json('labels')->nullable(); $t->timestamp('recorded_at'); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); $t->index(['metric','recorded_at']); });
        Schema::create('platform_logs', function (Blueprint $t) { $t->bigIncrements('id'); $t->uuid('tenant_id')->nullable()->index(); $t->string('level',20); $t->string('channel',50); $t->string('message'); $t->string('correlation_id',100)->nullable()->index(); $t->string('trace_id',100)->nullable()->index(); $t->json('context')->nullable(); $t->timestamp('occurred_at'); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); });
        Schema::create('alert_policies', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->nullable()->index(); $t->string('name'); $t->string('metric',100); $t->string('operator',10); $t->decimal('threshold',20,6); $t->json('delivery_channels'); $t->boolean('is_active')->default(true); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); });
        Schema::create('operation_incidents', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('alert_policy_id')->nullable(); $t->uuid('tenant_id')->nullable()->index(); $t->string('severity',20); $t->string('status',20)->default('open'); $t->string('title'); $t->json('details')->nullable(); $t->timestamp('opened_at'); $t->timestamp('resolved_at')->nullable(); $t->timestamps(); $t->foreign('alert_policy_id')->references('id')->on('alert_policies')->nullOnDelete(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); });
        Schema::create('operation_runs', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('run_type',40); $t->string('name'); $t->string('status',20); $t->json('metadata')->nullable(); $t->timestamp('started_at'); $t->timestamp('completed_at')->nullable(); $t->timestamps(); });
        Schema::create('tenant_operation_snapshots', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->json('usage'); $t->json('health'); $t->timestamp('snapshotted_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('platform_releases', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('version')->unique(); $t->string('status',20); $t->json('features')->nullable(); $t->json('migrations')->nullable(); $t->timestamp('deployed_at')->nullable(); $t->timestamps(); });
        Schema::create('operation_audits', function (Blueprint $t) { $t->uuid('id')->primary(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->uuid('tenant_id')->nullable()->index(); $t->string('action',80); $t->string('subject_type',80)->nullable(); $t->string('subject_id',80)->nullable(); $t->string('correlation_id',100)->nullable(); $t->json('metadata')->nullable(); $t->timestamp('occurred_at'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->nullOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('operation_audits'); Schema::dropIfExists('platform_releases'); Schema::dropIfExists('tenant_operation_snapshots'); Schema::dropIfExists('operation_runs'); Schema::dropIfExists('operation_incidents'); Schema::dropIfExists('alert_policies'); Schema::dropIfExists('platform_logs'); Schema::dropIfExists('platform_metrics'); Schema::dropIfExists('health_check_results'); Schema::dropIfExists('health_check_definitions'); }
};
