<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('asset_categories', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->json('rules')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->unique(['tenant_id','name']); });
        Schema::create('assets', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('asset_number',50); $t->string('asset_tag')->nullable(); $t->string('serial_number')->nullable(); $t->string('barcode')->nullable(); $t->string('qr_code')->nullable(); $t->uuid('category_id')->nullable(); $t->string('brand')->nullable(); $t->string('model')->nullable(); $t->string('manufacturer')->nullable(); $t->string('vendor')->nullable(); $t->date('purchase_date')->nullable(); $t->decimal('purchase_cost',15,2)->nullable(); $t->date('warranty_start')->nullable(); $t->date('warranty_end')->nullable(); $t->string('depreciation_method',30)->nullable(); $t->decimal('depreciation_rate',8,4)->nullable(); $t->decimal('current_value',15,2)->nullable(); $t->string('status',30)->default('available'); $t->uuid('branch_id')->nullable(); $t->uuid('department_id')->nullable(); $t->string('location')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('category_id')->references('id')->on('asset_categories')->nullOnDelete(); $t->foreign('branch_id')->references('id')->on('branches')->nullOnDelete(); $t->foreign('department_id')->references('id')->on('departments')->nullOnDelete(); $t->unique(['tenant_id','asset_number']); });
        Schema::create('asset_assignments', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('asset_id')->index(); $t->string('assignee_type',30); $t->string('assignee_id',80); $t->string('assignment_type',30); $t->timestamp('assigned_at'); $t->timestamp('due_back_at')->nullable(); $t->timestamp('returned_at')->nullable(); $t->string('status',20)->default('active'); $t->json('handover_document_ids')->nullable(); $t->timestamps(); $t->foreign('asset_id')->references('id')->on('assets')->cascadeOnDelete(); });
        Schema::create('asset_requests', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->uuid('category_id')->nullable(); $t->text('description')->nullable(); $t->string('status',20)->default('draft'); $t->uuid('workflow_instance_id')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->cascadeOnDelete(); $t->foreign('category_id')->references('id')->on('asset_categories')->nullOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('asset_returns', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('assignment_id')->index(); $t->string('condition',30); $t->json('accessories')->nullable(); $t->text('comments')->nullable(); $t->decimal('damage_cost',15,2)->nullable(); $t->json('document_ids')->nullable(); $t->timestamp('returned_at'); $t->timestamps(); $t->foreign('assignment_id')->references('id')->on('asset_assignments')->cascadeOnDelete(); });
        Schema::create('asset_maintenances', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('asset_id')->index(); $t->string('maintenance_type',30); $t->string('vendor')->nullable(); $t->decimal('cost',15,2)->nullable(); $t->date('scheduled_for')->nullable(); $t->date('completed_on')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); $t->foreign('asset_id')->references('id')->on('assets')->cascadeOnDelete(); });
        Schema::create('software_licenses', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->string('license_key')->nullable(); $t->unsignedInteger('seats')->default(1); $t->unsignedInteger('assigned_seats')->default(0); $t->string('vendor')->nullable(); $t->date('expires_at')->nullable(); $t->decimal('cost',15,2)->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('software_licenses'); Schema::dropIfExists('asset_maintenances'); Schema::dropIfExists('asset_returns'); Schema::dropIfExists('asset_requests'); Schema::dropIfExists('asset_assignments'); Schema::dropIfExists('assets'); Schema::dropIfExists('asset_categories'); }
};
