<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('separation_cases', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id'); $t->string('separation_type',40); $t->string('reason')->nullable(); $t->date('submitted_on')->nullable(); $t->date('last_working_date')->nullable(); $t->string('status',20)->default('draft'); $t->uuid('workflow_instance_id')->nullable(); $t->json('attachments')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->restrictOnDelete(); $t->foreign('workflow_instance_id')->references('id')->on('workflow_instances')->nullOnDelete(); });
        Schema::create('exit_checklist_templates', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->string('name'); $t->json('assignment_rules')->nullable(); $t->json('tasks'); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); });
        Schema::create('exit_checklist_tasks', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('separation_case_id')->index(); $t->string('department'); $t->uuid('owner_employee_id')->nullable(); $t->string('title'); $t->string('status',20)->default('pending'); $t->date('due_date')->nullable(); $t->text('comments')->nullable(); $t->json('document_ids')->nullable(); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->foreign('separation_case_id')->references('id')->on('separation_cases')->cascadeOnDelete(); $t->foreign('owner_employee_id')->references('id')->on('employees')->nullOnDelete(); });
        Schema::create('knowledge_transfers', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('separation_case_id')->unique(); $t->uuid('successor_employee_id')->nullable(); $t->longText('handover_notes')->nullable(); $t->json('document_ids')->nullable(); $t->string('status',20)->default('pending'); $t->timestamps(); $t->foreign('separation_case_id')->references('id')->on('separation_cases')->cascadeOnDelete(); $t->foreign('successor_employee_id')->references('id')->on('employees')->nullOnDelete(); });
        Schema::create('exit_interviews', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('separation_case_id')->unique(); $t->json('responses')->nullable(); $t->boolean('is_anonymous')->default(false); $t->json('document_ids')->nullable(); $t->timestamps(); $t->foreign('separation_case_id')->references('id')->on('separation_cases')->cascadeOnDelete(); });
        Schema::create('final_settlements', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('separation_case_id')->unique(); $t->uuid('payroll_run_id')->nullable(); $t->decimal('gross_amount',15,2)->default(0); $t->decimal('deductions',15,2)->default(0); $t->decimal('net_payable',15,2)->default(0); $t->string('status',20)->default('pending'); $t->timestamps(); $t->foreign('separation_case_id')->references('id')->on('separation_cases')->cascadeOnDelete(); $t->foreign('payroll_run_id')->references('id')->on('payroll_runs')->nullOnDelete(); });
        Schema::create('alumni_profiles', function (Blueprint $t) { $t->uuid('id')->primary(); $t->uuid('tenant_id')->index(); $t->uuid('employee_id')->unique(); $t->string('personal_email')->nullable(); $t->boolean('rehire_eligible')->default(true); $t->boolean('is_blacklisted')->default(false); $t->date('cooling_until')->nullable(); $t->json('profile')->nullable(); $t->timestamps(); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreign('employee_id')->references('id')->on('employees')->restrictOnDelete(); });
    }
    public function down(): void { Schema::dropIfExists('alumni_profiles'); Schema::dropIfExists('final_settlements'); Schema::dropIfExists('exit_interviews'); Schema::dropIfExists('knowledge_transfers'); Schema::dropIfExists('exit_checklist_tasks'); Schema::dropIfExists('exit_checklist_templates'); Schema::dropIfExists('separation_cases'); }
};
